### ISSUE TITLE
*.pb.h和*.pb.cc之类的文件是怎么生成的？

### ISSUE THREAD

**Issue by w359405949** [HW140701/GoogleMediapipePackageDll#10]
你的文章和截图里面，这些文件直接就有。
但bazel build的时候，这些文件似乎在悄悄生成的某个位置，构建完成后就被bazel悄悄删除了。

**Comment by HW140701** [comment]
你觉得有问题就拉mediapipev0.8.6版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cangqiong ***@***.***&gt;
发送时间: 2022年4月25日 07:33
收件人: HW140701/GoogleMediapipePackageDll ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[HW140701/GoogleMediapipePackageDll] *.pb.h和*.pb.cc之类的文件是怎么生成的？ (Issue #10)





 
你的文章和截图里面，这些文件直接就有。
 但bazel build的时候，这些文件似乎在悄悄生成的某个位置，构建完成后就被bazel悄悄删除了。
