### ISSUE TITLE
HandTracking DLL building failed

### ISSUE THREAD

**Issue by mauricewells** [HW140701/GoogleMediapipePackageDll#11]
![image](https://user-images.githubusercontent.com/96590277/166740547-d2b19c63-dbfc-4d68-892a-b772f18a67e5.png)

**Comment by mauricewells** [comment]
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="E://Installed_app//python37//python.exe" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures
I gave command like above for building dll
but error was made
who can explain why it occurs?

**Comment by HW140701** [comment]
Please use the v0.8.6 version to compile. I haven't tested the latest version, but some people have succeeded. If you want a perfect compilation is to use version 0.8.6, which I explained in detail in the README, please check the instructions carefully.
