### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Carringbrink** [HW140701/GoogleMediapipePackageDll#12]
作者您好，我按照的您的编译过程出现了这个报错，我的版本和您都保持一致的

![image](https://user-images.githubusercontent.com/104354080/166887377-cb886a9d-d9f2-40d8-a1da-c5f257da7f07.png)

**Comment by HW140701** [comment]
看报错是HandUpHandDownDetect类的构造函数和析构函数没有定义，不可能啊，在HandUpHandDownDetect.cpp里面有定义的

**Comment by Carringbrink** [comment]
是的，作者,关于hand_up_hand_down_detect.cpp和hand_up_hand_down_detect.h我是直接在你的github项目中拷的，一开始我没有加入这两个文件，后面报错找不到，但是当我加入后就变成了这个问题

**Comment by Carringbrink** [comment]
是的作者，确实存在缓存，目前手势追踪编译并且可运行，但是当我编译全身追踪的时候出现了这个错误，我看了下源文件发现您也声明了这些变量，但是我解决不了这个问题，您可以看下吗

![image](https://user-images.githubusercontent.com/104354080/166920293-ccb58c28-0afc-485d-97bc-de42ba385afd.png)

**Comment by HW140701** [comment]
啊？重新拉下仓库再编译下吧

**Comment by Carringbrink** [comment]
作者我按您的仓库重新更新了下，但是我编译还是报错，他是两个不同的报错来回出现，您如果方便的话看下问题在哪
![image](https://user-images.githubusercontent.com/104354080/167083009-e649878b-b192-49a1-8e19-bc15b6b20f10.png)
![image](https://user-images.githubusercontent.com/104354080/167083036-2a75e2a0-cda0-4b3a-a2a1-9098516a2654.png)

**Comment by HW140701** [comment]
这个我也不知道，cpp里面是有声明的

**Comment by Carringbrink** [comment]
好的作者，非常感谢您的耐心回答
