### ISSUE TITLE
怎样自己编译得到可执行文件

### ISSUE THREAD

**Issue by mxer** [HW140701/GoogleMediapipePackageDll#13]
作者您好，感谢您的分享。我按照您的步骤，已经顺利编译得到动态库，但是我没有看到得到可执行文件的编译文件和编译命令，如果我想自己编译得到可执行文件，需要怎么做呢，谢谢！

**Comment by HW140701** [comment]
没看懂你说的是什么意思。
如果是要使用动态库的可执行程序的例子看这：[https://github.com/HW140701/GoogleMediapipePackageDll/tree/main/dll_use_example/MediapipePackageDllTest](https://github.com/HW140701/GoogleMediapipePackageDll/tree/main/dll_use_example/MediapipePackageDllTest)

**Comment by mxer** [comment]
> 没看懂你说的是什么意思。 如果是要使用动态库的可执行程序的例子看这：https://github.com/HW140701/GoogleMediapipePackageDll/tree/main/dll_use_example/MediapipePackageDllTest

是的，我已经运行了可执行文件，但如果我想自己编译得到这个可执行文件，要怎么做呢，要自己编写BUILD文件吗

**Comment by HW140701** [comment]
这不是很显然的vs工程吗？为什么还要build文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mxer ***@***.***&gt;
发送时间: 2022年6月1日 11:53
收件人: HW140701/GoogleMediapipePackageDll ***@***.***&gt;
抄送: HW140701 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[HW140701/GoogleMediapipePackageDll] 怎样自己编译得到可执行文件 (Issue #13)





  
没看懂你说的是什么意思。 如果是要使用动态库的可执行程序的例子看这：https://github.com/HW140701/GoogleMediapipePackageDll/tree/main/dll_use_example/MediapipePackageDllTest
  
是的，我已经运行了可执行文件，但如果我想自己编译得到这个可执行文件，要怎么做呢，要自己编写BUILD文件吗

**Comment by mxer** [comment]
> 这不是很显然的vs工程吗？为什么还要build文件 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: mxer ***@***.***&gt; 发送时间: 2022年6月1日 11:53 收件人: HW140701/GoogleMediapipePackageDll ***@***.***&gt; 抄送: HW140701 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[HW140701/GoogleMediapipePackageDll] 怎样自己编译得到可执行文件 (Issue #13) 没看懂你说的是什么意思。 如果是要使用动态库的可执行程序的例子看这：https://github.com/HW140701/GoogleMediapipePackageDll/tree/main/dll_use_example/MediapipePackageDllTest 是的，我已经运行了可执行文件，但如果我想自己编译得到这个可执行文件，要怎么做呢，要自己编写BUILD文件吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哦哦，好的，多谢
