### ISSUE TITLE
按照编译命令运行，一直在报这两个错

### ISSUE THREAD

**Issue by sweetsmile888** [HW140701/GoogleMediapipePackageDll#14]
按照编译命令运行，运行一次报错误1，再运行1次报错误2。。。。一直这样
错误1.
mediapipe/examples/desktop/holistic_tracking_dll/ArmUpAndDownRecognition.cpp(27): error C2181: 没有匹配 if 的非法 else
mediapipe/examples/desktop/holistic_tracking_dll/ArmUpAndDownRecognition.cpp(36): error C2181: 没有匹配 if 的非法 else
错误2：
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(20): error C2065: “thumb_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(21): error C2065: “thumb_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(27): error C2065: “thumb_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(59): error C2065: “ring_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(60): error C2065: “ring_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(66): error C2065: “ring_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(70): error C2065: “pink_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(71): error C2065: “pink_vec1”: 未声明的标识符
mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(77): error C2065: “pink_vec1”: 未声明的标识符

**Comment by HW140701** [comment]
这不是我的问题，仔细检查你的编译环境是否ok，代码是否正常

**Comment by sweetsmile888** [comment]
环境没一点问题，官方的所有demo我都编译完了，没出错，难道是medieapipe版本的问题？不应该啊，这都是最基本的语法错误提示

**Comment by sweetsmile888** [comment]
环境没一点问题，官方的所有demo我都编译完了，没出错，难道是medieapipe版本的问题？不应该啊，这都是最基本的语法错误提示

**Comment by HW140701** [comment]
先使用指定的Mediapipe v0.8.6吧

**Comment by zhangyux15** [comment]
用最新的bazel5.3编译即可

**Comment by zhuchenpeng** [comment]
> 按照编译命令运行，运行一次报错误1，再运行1次报错误2。。。。一直这样 错误1. mediapipe/examples/desktop/holistic_tracking_dll/ArmUpAndDownRecognition.cpp(27): error C2181: 没有匹配 if 的非法 else mediapipe/examples/desktop/holistic_tracking_dll/ArmUpAndDownRecognition.cpp(36): error C2181: 没有匹配 if 的非法 else 错误2： mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(20): error C2065: “thumb_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(21): error C2065: “thumb_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(27): error C2065: “thumb_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(59): error C2065: “ring_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(60): error C2065: “ring_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(66): error C2065: “ring_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(70): error C2065: “pink_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(71): error C2065: “pink_vec1”: 未声明的标识符 mediapipe/examples/desktop/holistic_tracking_dll/GestureRecognition.cpp(77): error C2065: “pink_vec1”: 未声明的标识符

I faced similar problem, did you solve it now?

**Comment by zhuchenpeng** [comment]
![image](https://user-images.githubusercontent.com/116131840/200756482-b07feb46-9235-4e29-9cf2-57d18afe7189.png)

**Comment by zxk19981227** [comment]
这个我怀疑是bazel的协议采用的是c98……所以必须在第一行声明变量
