### ISSUE TITLE
debug 正常运行 release 发生异常

### ISSUE THREAD

**Issue by yunshangyue71** [HW140701/GoogleMediapipePackageDll#15]

**Comment by yunshangyue71** [comment]
if (mediapipeHolisticTrackingDll.m_MediapipeHolisticTrackingInit(mediapipe_holistic_tracking_model_path.c_str(),true,true,true,true))
这里显示的是访问时候发生冲突， 但是debug 的时候没有问题。请教一下

**Comment by HW140701** [comment]
可能是Mediapipe 官方的模型在Release模式下放置的的位置有误吧，估计是路径问题

**Comment by yunshangyue71** [comment]
这个路径写在哪里了呢？比如您的debug没问题，我想看看您debug的路径是怎么指定的。多谢

**Comment by HW140701** [comment]
你是否对我的仓库做了修改，如果没有做修改应该不会出现这个问题

**Comment by yunshangyue71** [comment]
没有修改，我将您的项目整体下载下来放在了C盘C:\work\mediapipe_dll\GoogleMediapipePackageDll-main\GoogleMediapipePackageDll-main\dll_use_example\MediapipePackageDllTest\projectfile， 运行的sln

**Comment by yunshangyue71** [comment]
我自己下载的原始的mediapipe 进行的编译，想仿照您的这个test实现这个mediapipe的功能，并集成到其他的项目中。您的这个test，我想对照一下，看看集成的差异

**Comment by HW140701** [comment]
如果是在vs下Release模式下运行，不要点调试，请使用ctrl+f5直接运行项目，我猜肯定是点调试按钮运行

**Comment by yunshangyue71** [comment]
大佬，确实是这个原因，这个我怎么改一下，就可以调试了呢？

**Comment by HW140701** [comment]
调试为什么要在Release模式下？搞不懂了 你这个有点奇怪啊 小白？

**Comment by yunshangyue71** [comment]
抱歉哈，我对C++ 不是很熟悉， 目前正在摸索着使用。目前我一直是release 下进行调试的，调试完毕，就好了

**Comment by HW140701** [comment]
请在debug模式下调试

**Comment by yunshangyue71** [comment]
嗯， 多谢了
