### ISSUE TITLE
关于项目的Windows Arm64版本的编译

### ISSUE THREAD

**Issue by GreenShadeZhang** [HW140701/GoogleMediapipePackageDll#19]
感觉这个项目可以继续发展，然后像opencvsharp那样封装成c#版本的，结合ml.net可以为.net生态代码机器视觉相关的开箱即用的功能了。

**Comment by HW140701** [comment]
做成C#也就只是差了导入dll接口的这一步，没什么区别

**Comment by GreenShadeZhang** [comment]
> 做成C#也就只是差了导入dll接口的这一步，没什么区别

我主要对c++不太熟 你封装的这些c++代码有用在unity过吗 我想把它集成到桌面软件里 感觉你这个方案算是比较优雅的了

**Comment by HW140701** [comment]
我只能告诉你这个肯定是可以在unity中用的，建议度娘C#导入C++dll接口，其他的逻辑参考C++ use demo

**Comment by GreenShadeZhang** [comment]
> 我只能告诉你这个肯定是可以在unity中用的，建议度娘C#导入C++dll接口，其他的逻辑参考C++ use demo

ok 我找时间试试
