### ISSUE TITLE
handtracking 封装编译失败

### ISSUE THREAD

**Issue by junlin49** [HW140701/GoogleMediapipePackageDll#20]
你好，我在[[将Mediapipe handtracking封装成动态链接库dll/so](https://github.com/HW140701/GoogleMediapipePackageDll/issues/%5BMediapipe%20-%20%E5%B0%86Mediapipe%20handtracking%E5%B0%81%E8%A3%85%E6%88%90%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93dll/so,%E5%AE%9E%E7%8E%B0%E5%9C%A8%E6%A1%8C%E9%9D%A2%E5%BA%94%E7%94%A8%E4%B8%AD%E5%B5%8C%E5%85%A5%E6%89%8B%E5%8A%BF%E8%AF%86%E5%88%AB%E5%8A%9F%E8%83%BD%20-%20StubbornHuang%20Blog%5D(https://www.stubbornhuang.com/1562/#ftoc-heading-12))]([Mediapipe - 将Mediapipe handtracking封装成动态链接库dll/so,实现在桌面应用中嵌入手势识别功能 - StubbornHuang Blog](https://www.stubbornhuang.com/1562/#ftoc-heading-12))按步骤进行动态链接库编译时遇到了以下问题，网络上没有查到有用的解决方法，希望能不吝赐教。

环境：

- Windows10
- VS2019
- mediapipe v0.9.1
- bazel bazel-7.0.0-pre.20230209.2

问题描述：

![image-20230224225137954](https://raw.githubusercontent.com/junlin49/imageRepo/main/202302242251205.png)

![image-20230224224721364](https://raw.githubusercontent.com/junlin49/imageRepo/main/202302242247435.png)

![](https://raw.githubusercontent.com/junlin49/imageRepo/main/202302242245820.png)

![image-20230224224744315](https://raw.githubusercontent.com/junlin49/imageRepo/main/202302242247381.png)

使用命令```bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\\Anaconda3\\envs\\tensorflow\\python.exe" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures```编译动态链接库，mediapipe目录下```examples\desktop\hand_tracking_test```文件夹内有hand_gesture_recognition.cpp、hand_gesture_recognition.h、hand_tracking_api.cpp、hand_tracking_api.h、hand_tracking_data.h、hand_tracking_detect.cpp、hand_tracking_detect.h以及BUILD文件。

BUILD文件部分如下：

![image-20230224230111288](https://raw.githubusercontent.com/junlin49/imageRepo/main/202302242301316.png)

另外，在此环境下helloWorld可以成功编译。

**Comment by junlin49** [comment]
补充，D:\VS2019\VC\Tools\MSVC\14.29.30133\include\xtr1common文件部分内容如下：

![image-20230224231609196](https://raw.githubusercontent.com/junlin49/imageRepo/main/202302242316249.png)

![image-20230224231648420](https://raw.githubusercontent.com/junlin49/imageRepo/main/202302242316471.png)



嗯，，，不是很懂为什么在这里会报错

**Comment by HW140701** [comment]
如果按照这个博文每一步都是正确的，并且你的vs2019安装了c++，应该不会失败的，毕竟大多数人最后都成功了，估计是某个环节出了问题，也许你需要按步骤检查是否每一步都是正确的。从你的报错信息我也没有办法推测出具体的原因，不过看你的vs的安装路径是在d盘，我不知道这个是否有影响

**Comment by junlin49** [comment]
感谢回复，我尝试将bazel的编译变量换为VS2017，即更改```BAZEL_VS```,```BAZEL_VC```以及```BAZEL_VC_FULL_VERSION```，然而重新编译出来的结果和之前相比并没有区别，仍旧显示是VS2019编译，且编译失败，报错一致。后续打算换个电脑重新配置环境。

**Comment by junlin49** [comment]
问题解决，我重新安装了VS2019之后，还是出现此问题，之后我又卸载了全部VS，安装了VS2022，并且将多余的Windows SDK卸载了，只留下了一个版本，之后就没有此错误了。
