### ISSUE TITLE
关于mediapipe hand landmark detect c++

### ISSUE THREAD

**Issue by LiuYi-Up** [HW140701/GoogleMediapipePackageDll#21]
您好，非常感谢您的工作。
请问一下如果想要将手部关键点检测单独封装，可以大致怎么修改呢？
期待您的回复。
祝您工作顺利！

**Comment by HW140701** [comment]
建议先参考Mediapipe关于手部检测的示例，结合我的这个仓库做以下封装就好了，工作量估计不会很大

**Comment by LiuYi-Up** [comment]
> 建议先参考Mediapipe关于手部检测的示例，结合我的这个仓库做以下封装就好了，工作量估计不会很大

好的，非常感谢

**Comment by LiuYi-Up** [comment]
> 建议先参考Mediapipe关于手部检测的示例，结合我的这个仓库做以下封装就好了，工作量估计不会很大

您好，我是在Ubuntu下进行操作生成.so文件，然后我想要在我自己的c++项目里调用它，因为我是一个新手，但我不知道该怎么使用这个动态链接库，有以下几点困惑：

1.我是使用cmake来编译我的项目，我不知道该如何链接它？
2.我不知道需要将哪些文件复制到我的项目中，或者说需要进行哪些操作？

您能给些建议吗？
祝您天天开心！

**Comment by HW140701** [comment]
我没有在linux相关的环境下测试过，不过如果是你自己在这个基础上封装的so，就在cmake中按照动态链接库的方式链接即可，运行时需要mediapipe的相关模型文件，可参考本项目的模型放置位置

**Comment by LiuYi-Up** [comment]
> 我没有在linux相关的环境下测试过，不过如果是你自己在这个基础上封装的so，就在cmake中按照动态链接库的方式链接即可，运行时需要mediapipe的相关模型文件，可参考本项目的模型放置位置

您好，我基于您的仓库构建了c++动态链接库，并且成功运行了，但是结果好像只有一只手的坐标，我想问一下可以检测两只手吗？我不确定是不是我哪里配置错误了。

期望您的回复！
祝您笑口常开！

**Comment by HW140701** [comment]
肯定是可以检测两只手的。
我建议是你可以先编译下官方的hand tracking的例子，运行，如果可以正常的检测到两只手，那么可以参考官方示例排查你的代码错误。
