### ISSUE TITLE
关于创建多线程使用时，除了第一个线程中能正确初始化模型，第二或者第三线程初始化失败。

### ISSUE THREAD

**Issue by LiuYi-Up** [HW140701/GoogleMediapipePackageDll#22]
您好，我将生成的动态库添加到我的工程中使用时，我想要创建多线程监控多个摄像头，这个时候出现以下问题：

1. 第一个线程初始化能够初始化成功并正常运行模型；
2. 接着后面的线程中初始化就失败了，init failed，当我打开第二个线程中的摄像头以后，第一个线程也检测不了了。

上面两个问题我不知道是动态库只能一个线程使用还是有哪些地方没有设置正确。如果可以，期待您能够给点建议。

祝您天天开心，事事如意。

**Comment by HW140701** [comment]
我没有进行过多线程调用的尝试。
我估计是Mediapipe的问题吧，猜测应该是不能在多个线程中加载同一个模型，或者其Graph是独占的吧。
