### ISSUE TITLE
win10 fetching @local_execution_config_platform permission denied

### ISSUE THREAD

**Issue by YZCOrange** [HW140701/GoogleMediapipePackageDll#23]
大佬，您好，我在编译的时候出现了权限问题请问是什么原因呀，管理员打开cmd也是如此，看着像远程仓库的问题，但是换了好多个版本都不行，bazel和mediapipe都是官方推荐对应的版本。头疼至极，最近急需解决，还望大佬指点一二！
![image](https://github.com/HW140701/GoogleMediapipePackageDll/assets/43722924/ec586651-7a9f-4fb5-a5d0-0b78b0f6e001)

**Comment by HW140701** [comment]
也许需要试一下科学上网

**Comment by YZCOrange** [comment]
> 也许需要试一下科学上网

@HW140701 一直开着呢，还是报一样的错误

**Comment by YZCOrange** [comment]
> 也许需要试一下科学上网

其他库和包都下载完了，就遇到这个就报错了
