### ISSUE TITLE
在Win10下编译遇到问题

### ISSUE THREAD

**Issue by blueskyscorpio** [HW140701/GoogleMediapipePackageDll#24]
大神，在Win10下已经配置好C++编译环境，Hello World已经编译成功，但编译holistic_tracking_dll时遇到下面的错误，能帮看下是什么问题吗？多谢了

ERROR: C:/mediapipe/mediapipe/util/BUILD:161:11: Compiling mediapipe/util/annotation_renderer.cc failed: (Exit 2): cl.exe failed: error executing CppCompile command (from target //mediapipe/util:annotation_renderer)
  cd /d C:/users/shaohg/_bazel_shaohg/3vmcl3ou/execroot/mediapipe
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:\\Python38\\python.exe
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\shaohg\AppData\Local\Temp
    SET TMP=C:\Users\shaohg\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.obj.params
# Configuration: 70734f78ae1345e7cb6cb3703cf7a2355f11024e083a50cfef3a781ff8a205a6
# Execution platform: @local_execution_config_platform//:platform
mediapipe/util/annotation_renderer.cc(107): error C2660: 'DrawTextA': function does not take 1 arguments
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winuser.h(8171): note: see declaration of 'DrawTextA'
mediapipe/util/annotation_renderer.cc(533): error C2039: 'DrawTextA': is not a member of 'mediapipe::AnnotationRenderer'
.\mediapipe/util/annotation_renderer.h(48): note: see declaration of 'mediapipe::AnnotationRenderer'
mediapipe/util/annotation_renderer.cc(540): error C2065: 'image_width_': undeclared identifier
mediapipe/util/annotation_renderer.cc(540): error C2065: 'image_height_': undeclared identifier
mediapipe/util/annotation_renderer.cc(543): error C2065: 'image_height_': undeclared identifier
mediapipe/util/annotation_renderer.cc(545): error C2065: 'scale_factor_': undeclared identifier
mediapipe/util/annotation_renderer.cc(546): error C2065: 'scale_factor_': undeclared identifier
mediapipe/util/annotation_renderer.cc(547): error C2065: 'scale_factor_': undeclared identifier
mediapipe/util/annotation_renderer.cc(553): error C2065: 'scale_factor_': undeclared identifier
mediapipe/util/annotation_renderer.cc(552): error C2737: 'thickness': const object must be initialized
mediapipe/util/annotation_renderer.cc(556): error C3861: 'ComputeFontScale': identifier not found
mediapipe/util/annotation_renderer.cc(571): error C2065: 'scale_factor_': undeclared identifier
mediapipe/util/annotation_renderer.cc(569): error C2737: 'background_thickness': const object must be initialized
mediapipe/util/annotation_renderer.cc(574): error C2065: 'mat_image_': undeclared identifier
mediapipe/util/annotation_renderer.cc(576): error C2065: 'flip_text_vertically_': undeclared identifier
mediapipe/util/annotation_renderer.cc(578): error C2065: 'mat_image_': undeclared identifier
mediapipe/util/annotation_renderer.cc(580): error C2065: 'flip_text_vertically_': undeclared identifier
Target //mediapipe/examples/desktop/holistic_tracking_dll:MediapipeHolisticTracking failed to build
INFO: Elapsed time: 2.001s, Critical Path: 1.66s
INFO: 163 processes: 129 internal, 34 local.
ERROR: Build did NOT complete successfully

**Comment by HW140701** [comment]
这个问题我没有遇到过，是不是用的Mediapipe新版本代码编译的？如果使用新版本的代码编译的，可能会有问题吧

**Comment by blueskyscorpio** [comment]
是的，我是用Mediapipe最新版编译的。
那要是调整有什么建议吗？多谢指导

**Comment by HW140701** [comment]
看下README.md，试下用指定版本编译

**Comment by blueskyscorpio** [comment]
多谢了
