### ISSUE TITLE
打包成so包之后，dlopen(dynamicModulePath.c_str(), RTLD_LAZY);加载会报错时因为什么

### ISSUE THREAD

**Issue by Han-WG** [HW140701/GoogleMediapipePackageDll#26]
dll存在

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by Han-WG** [comment]
debug到 m_DynamicModulePtr = dlopen(dynamicModulePath.c_str(), RTLD_LAZY);这一行时会报错误：

Signal: SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x10))

我编译的时候没有出错

**Comment by HW140701** [comment]
> debug到 m_DynamicModulePtr = dlopen(dynamicModulePath.c_str(), RTLD_LAZY);这一行时会报错误：
> 
> Signal: SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x10))
> 
> 我编译的时候没有出错

先检查下你的so库路径是否正确，dlopen是否打开的是正确路径的so

**Comment by Han-WG** [comment]
路径是没有问题的，我换了别的so包，就可以加载成功，换了自己编译的so包就不行了
不知道编译过程中哪里出了问题，我编译是成功了的，编译了好几遍
用的是GoogleMediapipePackageDll/dll/hand_tracking_test/里的文件直接复制的
编译指令是
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="/home/hanwg/anaconda3/envs/torch/bin/python3" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures

唯一的修改是在BUILD里加了几行
![Screenshot from 2024-01-11 11-16-27](https://github.com/HW140701/GoogleMediapipePackageDll/assets/45985213/ac4d4f23-6ae1-44a8-ac64-e72d110555c5)

**Comment by Han-WG** [comment]
这是编译成功的界面

![Screenshot from 2024-01-11 11-35-26](https://github.com/HW140701/GoogleMediapipePackageDll/assets/45985213/97c6e7b1-27c6-4f44-b74c-c326ffcb4959)

**Comment by HW140701** [comment]
我没有实际在Ubuntu上编译和运行过这个项目，所以没有办法对你的问题提出建议。
无法加载so，使用ldd看下这个so链接的有些库是不是没有找到。
