### ISSUE TITLE
请教一下，如何能够区分左右手的坐标呢？

### ISSUE THREAD

**Issue by kyn817046** [HW140701/GoogleMediapipePackageDll#28]

**Comment by HW140701** [comment]
可以按照点的索引区分：https://www.stubbornhuang.com/1916/

**Comment by kyn817046** [comment]
mediapipe::Packet packet;
	mediapipe::Packet packet_landmarks;
	if (!m_pPoller->Next(&packet))
		return absl::OkStatus();

	if (m_pPoller_landmarks->QueueSize() > 0)
	{
		if (m_pPoller_landmarks->Next(&packet_landmarks))
		{

			std::vector<mediapipe::NormalizedLandmarkList> output_landmarks = packet_landmarks.Get<std::vector<mediapipe::NormalizedLandmarkList>>();
			//GestureRecognitionResult tempGestureResult;
			for (int m = 0; m < output_landmarks.size(); ++m)
			{
				mediapipe::NormalizedLandmarkList single_hand_NormalizedLandmarkList = output_landmarks[m];
				std::vector<mediapipe::ClassificationList> handedness;
				std::vector<PoseInfo> singleHandGestureInfo;
				singleHandGestureInfo.clear();
				for (int i = 0; i < single_hand_NormalizedLandmarkList.landmark_size(); ++i)
				{
					PoseInfo info;
					const mediapipe::NormalizedLandmark landmark = single_hand_NormalizedLandmarkList.landmark(i);
					info.x = landmark.x() * camera_frame.cols;
					info.y = landmark.y() * camera_frame.rows;
					singleHandGestureInfo.push_back(info);
				}
			}
我是看了您手势识别的代码，可以获取画面内俩只手的坐标，但是这俩组坐标点如何区分是左手还是右手的呢？

**Comment by kyn817046** [comment]
我找到文档里模型中输出handedness可以获取左右手，但是一不太清楚如何调用，您有空希望您可以解答，感谢

**Comment by HW140701** [comment]
可以看下holistic的代码，或者看下官方文档

**Comment by HW140701** [comment]
holistic里面是有区分的，
![image](https://github.com/HW140701/GoogleMediapipePackageDll/assets/23658564/c05c3048-fe2b-4699-b652-3520e1bf9951)

**Comment by kyn817046** [comment]
谢谢
