### ISSUE TITLE
在absl/flags資料夾中找不到flag.h和parse.h

### ISSUE THREAD

**Issue by chauncey1213** [HW140701/GoogleMediapipePackageDll#3]
您好,
我剛剛按照您的教學,
完成編譯並成功運行hello_world.exe
但要開始撰寫c++的code時,
在#include"absl/flags.flag.h"和
#include "absl/flags/parse.h"這兩列給出錯誤,
後來發現flags資料夾中沒有flag.h和parse.h這兩個檔案(我的python有安裝tensorflow)
請問這種現象是什麼地方發生問題呢?

**Comment by chauncey1213** [comment]
感謝您的回覆!
請問要怎麼編譯官方的例子呢?(不好意思我在這方面完全是新手)

**Comment by HW140701** [comment]
和编译helloworld差不多

**Comment by chauncey1213** [comment]
編譯發生error
ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace

**Comment by HW140701** [comment]
这个是你执行build命令的位置不是在那个仓库下，这些问题太基础了，为了节省大家的时间，建议你先熟读Mediapipe的官方网站的编译文档再去进行操作，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月16日(星期三) 晚上9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HW140701/GoogleMediapipePackageDll] 在absl/flags資料夾中找不到flag.h和parse.h (Issue #3)





 
編譯發生error
 ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
 See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chauncey1213** [comment]
> 这个是你执行build命令的位置不是在那个仓库下，这些问题太基础了，为了节省大家的时间，建议你先熟读Mediapipe的官方网站的编译文档再去进行操作，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年2月16日(星期三) 晚上9:58 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HW140701/GoogleMediapipePackageDll] 在absl/flags資料夾中找不到flag.h和parse.h (Issue #3) 編譯發生error ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file). See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by chauncey1213** [comment]
好的謝謝您的幫助

**Comment by chauncey1213** [comment]
問題已經解決了,感謝您的幫助。
