### ISSUE TITLE
How can I convert pose tracking  mediapipe c++ to dll  visual staduio c++ 2019 and  Dll import use it in C #, etc. Can you help me or code it?

### ISSUE THREAD

**Issue by problemSolvingProgramming** [HW140701/GoogleMediapipePackageDll#4]
How can I convert pose tracking  mediapipe c++ to dll  visual staduio c++ 2019 and  Dll import use it in C #, etc. Can you help me or code it?

**Comment by HW140701** [comment]
yeap.
This code repository already contains functionality to package hand tracking as a dll and use it in C# projects. Please read the link in the readme.md document carefully and read the code in the repository carefully, you can find everything you want.

**Comment by problemSolvingProgramming** [comment]
@HW140701 thank you. I read the readme. But in your repository, it's just HolisticTracking and hand tracking code, if that's my goal
https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/pose_tracking

Can use in C ++ and C #. I read your documents but for this I do not know exactly what to do and what code to write for pose_tracking that I can use in C #.

**Comment by HW140701** [comment]
> @HW140701 thank you. I read the readme. But in your repository, it's just HolisticTracking and hand tracking code, if that's my goal https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/pose_tracking
> 
> Can use in C ++ and C #. I read your documents but for this I do not know exactly what to do and what code to write for pose_tracking that I can use in C #.

Holistic tracking actually already includes the function of pose tracking. If you are not satisfied, you can refer to the code of this repository to extend post tracking, it is not difficult.

**Comment by problemSolvingProgramming** [comment]
@HW140701 Also, can you help me, how can I make a dll for pose tracking using basel, etc. For this example, I read your document, unfortunately you did not explain about it?

**Comment by problemSolvingProgramming** [comment]
@HW140701 Thank you. I liked your method, but unfortunately I need to use pose tracking mediapipe for the project, but I do not know exactly how to do it.

https://stackoverflow.com/questions/71297122/how-to-build-project-by-bazel-in-visual-studio-c-2019

I tried hard but unfortunately I did not succeed.

**Comment by HW140701** [comment]
> @HW140701 Thank you. I liked your method, but unfortunately I need to use pose tracking mediapipe for the project, but I do not know exactly how to do it.
> 
> https://stackoverflow.com/questions/71297122/how-to-build-project-by-bazel-in-visual-studio-c-2019
> 
> I tried hard but unfortunately I did not succeed.

My intention is for you to read the content contained in the link in the readme.md document.
Please refer [[to](https://www.stubbornhuang.com/1555/)](https://www.stubbornhuang.com/1555/) how to configure mediapipe C++ compilation environment in Windows system.
Please refer [[to](https://www.stubbornhuang.com/1562/)](https://www.stubbornhuang.com/1562/) and [https://www.stubbornhuang.com/1562/](https://www.stubbornhuang.com/1562/) how to use bazel to package handtracking and holistic tracking into dll in windows.
The [www.stubbornhuang.com](www.stubbornhuang.com) is my personal site，this is a Chinese site, if you can use chrome's translation tool for content translation.

**Comment by problemSolvingProgramming** [comment]
@HW140701 
thank you. I read these documents and according to the first document, I was able to create the exe file of the pose Tracking program, but for the second document, I do not know what code to write, so I referred to this document.
https://blog.csdn.net/haiyangyunbao813/article/details/119192951
This document puts the pose tracking codes, but unfortunately it is not complete, for example, posedata and poselandmark, I do not know what to do and what code to write.

**Comment by HW140701** [comment]
Are you chinese?
I have provided the source code and compiled files for reference. The packaging steps of most of Mediapipe's modules can refer to the code in this repository, but there are differences in some places. If you still don't know how to write your own functions, I don't think there's anything I can do.

**Comment by problemSolvingProgramming** [comment]
@HW140701 No, I'm not in China. I translate and read Chinese content through Google through Google Translate.
