### ISSUE TITLE
How can I cout the face landmark and hand landmark  pose landmark? Or a better question, what function can I use to receive or print values  pose landmark?

### ISSUE THREAD

**Issue by rigngsbase** [HW140701/GoogleMediapipePackageDll#5]
How can I cout the face landmark and hand landmark  pose landmark? Or a better question, what function can I use to receive or print values  pose landmark?

**Comment by HW140701** [comment]
yes.
you can see [https://github.com/HW140701/GoogleMediapipePackageDll/blob/86ae34ec2493f5544ef617241b09b3134377b742/dll/holistic_tracking_dll/HolisticTrackingDetect.cpp#L171](https://github.com/HW140701/GoogleMediapipePackageDll/blob/86ae34ec2493f5544ef617241b09b3134377b742/dll/holistic_tracking_dll/HolisticTrackingDetect.cpp#L171) . Starting from this line, it is to obtain relevant coordinate points such as face and pose.

**Comment by rigngsbase** [comment]
@HW140701 Thank you. I am going to print this pose landmark  in function main .. which is about 33 point . Can you help me what to do?

**Comment by HW140701** [comment]
It's not difficult, in fact, the code already includes this function.

**Comment by rigngsbase** [comment]
@HW140701 Thank you, please help me, I am a beginner.

**Comment by rigngsbase** [comment]
@HW140701  This function

absl :: Status GoogleMediapipeDetect :: HolisticTrackingDetect :: Mediapipe_RunMPPGraph_Direct (int image_width, int image_height, void * image_data, int * detect_result, bool show_result_image)

Returns the value absl :: Status if I add this code in the main function, it gives an error.So that I can print the value of pose or holstic landmarks.

**Comment by HW140701** [comment]
Please refer to my example to put the relevant model files of Mediapipe in the correct location. Of course, your example should compile correctly.
