### ISSUE TITLE
In some of your codes you wrote in Chinese, unfortunately it is not legible, for example, a sample

### ISSUE THREAD

**Issue by rigngsbase** [HW140701/GoogleMediapipePackageDll#6]
In some of your codes you wrote in Chinese, unfortunately it is not legible, for example, a sample :

![1477](https://user-images.githubusercontent.com/90084682/156922640-6ad35bc5-5542-40a2-b485-5d9cd419a08a.png)

![1488](https://user-images.githubusercontent.com/90084682/156922700-09606f14-fcdf-4313-abcb-e939b61930c0.png)

,....

**Comment by HW140701** [comment]
very sorry. The local encoding of some code files uses my computer's local encoding gbk instead of utf8. You can use other editors, such as sublime, notpadd++ to convert the file encoding format.
