### ISSUE TITLE
mediapipe版本确认

### ISSUE THREAD

**Issue by LebronJames0423** [HW140701/GoogleMediapipePackageDll#7]
你好，看了你的工程后，感觉写的很不错，我尝试复现你的工程，但是可能由于使用的mediapipe版本不一样，dll可以打包出来，但是在使用的时候，图像输出为黑屏，也没有手势识别结果。请问下你用的mediapipe是哪个版本的呢？能否提供你使用的版本的github下载链接啊？多谢

**Comment by HW140701** [comment]
![image](https://user-images.githubusercontent.com/23658564/159670845-a8702357-2bbf-4100-ad07-8fb210df4fda.png)

**Comment by LebronJames0423** [comment]
> ![image](https://user-images.githubusercontent.com/23658564/159670845-a8702357-2bbf-4100-ad07-8fb210df4fda.png)

OK

**Comment by LebronJames0423** [comment]
我这边用mediapipe 8.6版本，bazel 3.7.2 能够正常编译了，face_mesh也能够正常编译出来了，感谢
