### ISSUE TITLE
作者您好，我试了官方hello world 以及 pose tracking都可以编译，但holistic_tracking_dll出现以下报错，搜了很久一直没解决，能麻烦帮忙看下不，谢谢！

### ISSUE THREAD

**Issue by cellmigrate** [HW140701/GoogleMediapipePackageDll#8]
![image](https://user-images.githubusercontent.com/6167980/162705467-1ad0af71-970f-4399-b277-cf02576a3e3d.png)

`Compiling mediapipe/examples/desktop/holistic_tracking_dll/HolisticTrackingApi.cpp failed: undeclared inclusion(s) in rule '//mediapipe/examples/desktop/holistic_tracking_dll:MediapipeHolisticTracking':
this rule is missing dependency declarations for the following files included by 'mediapipe/examples/desktop/holistic_tracking_dll/HolisticTrackingApi.cpp':
  'external/com_google_absl/absl/flags/parse.h'
  'external/com_google_absl/absl/flags/internal/parse.h'
  'mediapipe/framework/port/opencv_highgui_inc.h'
  'mediapipe/framework/port/opencv_video_inc.h'
  'mediapipe/framework/port/parse_text_proto.h'
Target //mediapipe/examples/desktop/holistic_tracking_dll:MediapipeHolisticTracking failed to build`

**Comment by HW140701** [comment]
看错误是你这些头文件没有，但是不应该啊
我clone的Mediapipe的仓库有这些文件的

![image](https://user-images.githubusercontent.com/23658564/162708347-f87664ca-7d9c-41f5-9cf4-e520acac2db6.png)

**Comment by cellmigrate** [comment]
是的，我文件夹进去看过全都有的，也清除过bazel的缓存，重新跑了几次都是这样。我找到一个[类似情况](https://github.com/bazelbuild/bazel/issues/5640)说可能是在Windows运行的问题，但我看您教程应该也是在Windows上的，所以目前还没找到原因。

![image](https://user-images.githubusercontent.com/6167980/162860375-d518e06c-75c3-495f-8eb4-876ab24edfec.png)

**Comment by cellmigrate** [comment]
这是我目前项目文件位置：

![image](https://user-images.githubusercontent.com/6167980/162861895-3b4a896e-3aca-40a3-9204-9d893d29b43d.png)

这是里面的项目文件（未作修改）：

![image](https://user-images.githubusercontent.com/6167980/162862264-cb75223b-08ea-4cf7-8069-ab79aa6f1342.png)


这是bazel命令：

![image](https://user-images.githubusercontent.com/6167980/162861934-2e921018-f801-48dd-badb-13f1b955518e.png)

麻烦您帮忙看下是否哪里有问题。

**Comment by HW140701** [comment]
好像除了编译命令里面多了PYTHON_LIB_PATH这个之外没有其他的区别，你编译官方的其他例子有问题吗？或者你配置Mediapipe环境的时候没配置好？好像其他人没有出现这个问题

**Comment by cellmigrate** [comment]
我又试了官方的其他2个例子没问题（hand_tracking、holistic_tracking），现在我在build文件中加入了以下代码，能够编译成功，但是dll有27.4M，我看您生成的在5M左右，运行也有些问题，具体我会再研究下，谢谢

![image](https://user-images.githubusercontent.com/6167980/162878868-9f0c2275-b482-4fcc-8a2c-7e4d84041f35.png)
![image](https://user-images.githubusercontent.com/6167980/162879378-b226942a-9d2e-4db9-b159-10d18eee766c.png)

**Comment by zqlao** [comment]
@cellmigrate 碰到同样问题，请问您后来是怎么解决的？

**Comment by FunnyWii** [comment]
> hand_tracking

请问最后咋解决的？

> @cellmigrate 碰到同样问题，请问您后来是怎么解决的？

请问你最后解决了没
