### ISSUE TITLE
指针赋值的困惑

### ISSUE THREAD

**Issue by Kayce001** [HW140701/GoogleMediapipePackageDll#9]
学习c++不久，有些代码没看懂，请教一下。
m_Video_InputStreamName = "input_video";

	m_Video_OutputStreamName = "output_video";
	m_PoseLandmarks_OutputStreamName = "pose_landmarks";
	m_LeftHandLandmarks_OutputStreamName = "left_hand_landmarks";
	m_RightHandLandmarks_OutputStreamName = "right_hand_landmarks";
	m_FaceLandmarks_OutputStreamName = "face_landmarks";
像m_Video_OutputStreamName之类的不是指针吗，指针指向的不是地址吗？如果赋值的话不应该是*m_Video_OutputStreamName= “赋值”？

**Comment by HW140701** [comment]
额，这个也太....，建议百度或者google
